### ISSUE TITLE
Excuse me,I have some issue

### ISSUE THREAD

**Issue by Kimxu** [agusmakmun/flaskblog#1]
Thanks for your dedication，i want to build a blog that sse your project,but i see some problem of the project ——flaskblog

when i  used your process of guide ，i had some  problem of this project

/Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5 /Users/kimxu/Documents/KimxuBlog/flaskblog/__init__.py
Traceback (most recent call last):
  File "/Users/kimxu/Documents/KimxuBlog/flaskblog/__init__.py", line 19, in <module>
    register_blueprints(app)
  File "/Users/kimxu/Documents/KimxuBlog/flaskblog/__init__.py", line 13, in register_blueprints
    from views import posts
  File "/Users/kimxu/Documents/KimxuBlog/flaskblog/views.py", line 5, in <module>
    from models import (Post, Tag)
  File "/Users/kimxu/Documents/KimxuBlog/flaskblog/models.py", line 3, in <module>
    from flask_peewee.utils import slugify
ImportError: No module named 'flask_peewee'

Looking forward to your reply！

**Comment by agusmakmun** [comment]
are you already try with `pip install flask-peewee` ?
or to install all requirements, please following this:

```
$ pip install -r requirements.txt
```

**Comment by Kimxu** [comment]
yes ,i used the guide to build it ,but i discover the pkg-resources==0.0.0 can not to be build,and the project oopen the import is error. like this : from flaskblog import config (Unresolved reference 'flaskblog' less)

I'm just start to learn Python 
thanks for you .

**Comment by agusmakmun** [comment]
skip it.. i found that error as same as with my older project...

https://github.com/agusmakmun/flaskblog/commit/2dd10731fb8243cde7f14231e25112dba986e131

**Comment by Kimxu** [comment]
oh thanks ， the project can be running ,and i open  http://127.0.0.1:5000/  .... no has reaction ,is 

Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

what can i do it ..... please give me some guide.... thank you very much

**Comment by agusmakmun** [comment]
what going on in your terminal?
are you already has an mongodb?

**Comment by Kimxu** [comment]
when i access http://127.0.0.1:5000/admin ，The browser is show 
Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

and the console show：
/Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5 /Users/kimxu/Documents/KimxuBlog/flaskblog/flaskblog/**init**.py
- Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
  [2016-11-06 14:52:40,359] ERROR in app: Exception on / [GET]
  Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(_args, *_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/views.py", line 149, in dispatch_request
    return meth(_args, *_kwargs)
  File "/Users/kimxu/Documents/KimxuBlog/flaskblog/flaskblog/views.py", line 14, in get
    posts = Post.objects.paginate(page=page, per_page=config.per_page)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mongoengine/queryset/manager.py", line 37, in __get__
    queryset = queryset_class(owner, owner._get_collection())
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mongoengine/document.py", line 209, in _get_collection
    cls.ensure_indexes()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mongoengine/document.py", line 765, in ensure_indexes
    collection.create_index(fields, background=background, **opts)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pymongo/collection.py", line 1387, in create_index
    self.__create_index(keys, kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pymongo/collection.py", line 1294, in __create_index
    with self._socket_for_writes() as sock_info:
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pymongo/mongo_client.py", line 762, in _get_socket
    server = self._get_topology().select_server(selector)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pymongo/topology.py", line 210, in select_server
    address))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pymongo/topology.py", line 186, in select_servers
    self._error_message(selector))
  pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 61] Connection refused
  127.0.0.1 - - [06/Nov/2016 14:52:40] "GET / HTTP/1.1" 500 -
  [2016-11-06 14:53:10,595] ERROR in app: Exception on / [GET]

**Comment by Kimxu** [comment]
yes i have mongodb ..... but I don't know how to go to config the mongodb..

**Comment by agusmakmun** [comment]
Please read this: https://www.digitalocean.com/community/tutorials/how-to-install-mongodb-on-ubuntu-14-04 or other same tutorials.

**Comment by Kimxu** [comment]
thanks i go to see it now.
Wish you a happy life.  👍

**Comment by agusmakmun** [comment]
u're welcome, can i close this issue?

**Comment by Kimxu** [comment]
ok thanks
